name: plasma_wallet
description: "Interact with the Plasma blockchain and bridge."
publish_to: 'none'

version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # UI + Theming
  flex_color_scheme: ^7.3.1
  flutter_svg: ^2.0.10+1

  # Routing
  go_router: ^14.2.0

  # State Management + Generation
  hooks_riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  provider: ^6.1.2 #TODO: Migrate away from provider

  # Utils
  intl: ^0.19.0
  fpdart: ^1.1.0
  fetch_client: ^1.1.2
  http: ^1.2.1 #TODO: Migrate to fetch_client
  fixnum: ^1.1.0

  #Misc
  uuid: ^4.2.1
  crypto: ^3.0.3
  grpc: ^4.0.1

  # Blockchain
  plasma_protobuf: ^0.1.0
  plasma_sdk: ^0.0.0
  plasma_service_kit: ^0.0.0
  convert: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/