services:
  plasmanode:
    image: stratalab/plasma-node:dev
    ports:
      - "9084:9084"
  bitcoin:
    image: stratalab/bitcoin-zmq:v25-regtest
    ports:
      - "18444:18444"
      - "18443:18443"
      - "28332:28332"
  bridgeconsensus:
    build:
      context: bridge-consensus
      dockerfile: bridge-consensus.Dockerfile
    depends_on:
      plasmanode:
        condition: service_started
      bitcoin:
        condition: service_started
      bridge_init:
        condition: service_completed_successfully
    volumes:
      - wallet:/app/wallet
      - ./peg-in-wallet.json:/app/btc-wallet/peg-in-wallet.json
      - ./btc-wallet.json:/app/btc-wallet/btc-wallet.json
      - ./bridge-consensus/bridge_custom_launch.sh:/bridge_custom_launch.sh
      - ./bridge-consensus/application.conf:/application.conf
  bridgepublicapi:
    image: ghcr.io/plasmalaboratories/plasma-btc-bridge-public-api:latest
    command:
      - "--config-file"
      - "/application.conf"
    ports:
      - "5000:5000"
    depends_on:
      plasmanode:
        condition: service_started
      bitcoin:
        condition: service_started
      bridge_init:
        condition: service_completed_successfully
    volumes:
      - wallet:/app/wallet
      - ./bridge-public-api/application.conf:/application.conf
  envoy:
    build:
      context: envoy
      dockerfile: envoy.Dockerfile
    ports:
      - "9094:9094"
    links:
      - plasmanode
    volumes:
      - ./envoy/config.yaml:/etc/envoy/config.yaml
  bridge_init:
    build:
      context: init
      dockerfile: bridge-init.Dockerfile
    volumes:
      - wallet:/app/wallet
      - ./init/bridge_init.sh:/bridge_init.sh
    depends_on:
      - plasmanode

volumes:
  wallet:
