services:
  bifrost:
    image: toplprotocol/bifrost-node:dev
    ports:
      - "9084:9084"
  bitcoin:
    image: toplprotocol/bitcoin-zmq:v25-regtest
    ports:
      - "18444:18444"
      - "18443:18443"
      - "28332:28332"
  bridge:
    build:
      context: .
      dockerfile: bridge-run.Dockerfile
    command:
      - "--topl-host"
      - "bifrost"
      - "--btc-url"
      - "http://bitcoin"
      - "--topl-wallet-seed-file"
      - "/wallet/topl-wallet.json"
      - "--topl-wallet-db"
      - "/wallet/topl-wallet.db"
      - "--btc-peg-in-seed-file"
      - "/btc-wallet/peg-in-wallet.json"
      - "--btc-wallet-seed-file"
      - "/btc-wallet/btc-wallet.json"
    ports:
      - "4000:4000"
    depends_on:
      bifrost:
        condition: service_started
      bitcoin:
        condition: service_started
      bridge_init:
        condition: service_completed_successfully
    volumes:
      - wallet:/wallet
      - ./peg-in-wallet.json:/btc-wallet/peg-in-wallet.json
      - ./btc-wallet.json:/btc-wallet/btc-wallet.json
  bridge_init:
    image: sbtscala/scala-sbt:eclipse-temurin-jammy-11.0.22_7_1.9.8_3.3.1
    volumes:
      - wallet:/wallet
      - ./bridge_init.sh:/bridge_init.sh
    command: ["/bin/sh", "/bridge_init.sh"]
    depends_on:
      - bifrost

volumes:
  wallet: